# INTRODUZIONE ALLA LIBRERIA NUMPY

In [32]:
import numpy as np
# https://numpy.org/doc/stable/reference/arrays.html

In [33]:
arr = np.array([[0,0,0,0], [0,3,2,0]])

In [34]:
arr.shape
#arr.size

(2, 4)

In [35]:
arr2 = np.array([0,1,2,3,4])

In [36]:
arr2.shape

(5,)

In [37]:
#arr?

In [38]:
arr2 = np.arange(5) # crea un array intero crescente a partire da 0
# si possono creare di step personalizzati con start e stop personalizzati con np.arange

In [39]:
arr2

array([0, 1, 2, 3, 4])

In [40]:
l=[1,2]

In [41]:
np.asarray(l)

array([1, 2])

In [42]:
l?

Type:        list
String form: [1, 2]
Length:      2
Docstring:  
Built-in mutable sequence.

If no argument is given, the constructor creates a new empty list.
The argument must be an iterable if specified.


# Differenza tra liste e numpy array
- Le liste sono native di python, mentre gli array sono della libreria numpy
- Le liste possono contenere tipi eterogenei, mentre gli array hanno elementi omogenei (o meglio *dovrebbero*)

# Perché usare gli array con numpy
Gli array hanno avanzati metodi di manipolazione dati che sono sia più facili per il programmatore sia più efficienti rispetto alle liste. 
Dunque per calcoli onerosi è consigliato usare quest'ultimi

## Esempio:

In [43]:
lista1 = [1,2,3]
lista2 = [7,8,9]
for coord in zip(lista1,lista2):
    print(coord)

(1, 7)
(2, 8)
(3, 9)


In [44]:
import time
# Defining the size of the arrays
SIZE = 2000000

# Creating lists and NumPy arrays of integers from 0 to SIZE - 1
list1 = range(SIZE)
list2 = range(SIZE)
arra1 = np.arange(SIZE)
arra2 = np.arange(SIZE)

# Measuring the time taken to aggregate elements from each iterable using a list comprehension
start_list = time.time()  # Marking the start time
result = [(x, y) for x, y in zip(list1, list2)]  # Aggregating elements from 'list1' and 'list2' using list comprehension
print("Time to aggregate elements from each of the iterables:")
print("List:")
print((time.time() - start_list) * 1000)  # Printing the execution time in milliseconds

# Measuring the time taken to add NumPy arrays element-wise
start_array = time.time()  # Marking the start time
result = arra1 + arra2  # Performing element-wise addition on 'arra1' and 'arra2' using NumPy
print("NumPy array:")
print((time.time() - start_array) * 1000)  # Printing the execution time in milliseconds


Time to aggregate elements from each of the iterables:
List:
373.0740547180176
NumPy array:
92.97728538513184


In [45]:
diag = np.eye(5, dtype=int)
ones = np.ones(5)
zeros = np.zeros(5)
lin = np.linspace(0, 20, num=5)
r = np.random.default_rng()
r.random(3)

array([0.57674085, 0.37995673, 0.62853058])

In [46]:
emp = np.empty(5) # crea un array vuoto. Vuoto nel senso che non cambia lo stato delle celle di memoria che vengono assegnate all'array

In [47]:
emp

array([1.11703892e-311, 4.67296746e-307, 1.69121096e-306, 1.42417901e-306,
       1.84565979e-317])

In [48]:
lin

array([ 0.,  5., 10., 15., 20.])

In [49]:
diag*[5,4,3,2,1] #supporta anche la moltiplicazione con scalari

array([[5, 0, 0, 0, 0],
       [0, 4, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 2, 0],
       [0, 0, 0, 0, 1]])

In [50]:
newd = diag*[2,0,1,3,0] #supporta la moltiplicazione tra liste e array (compatibilmente con le regole di moltiplicazione matriciale)

In [51]:
conc = np.sort(newd) # ordina gli array

In [52]:
conc

array([[0, 0, 0, 0, 2],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 3],
       [0, 0, 0, 0, 0]])

In [53]:
# ordinare un array
np.sort(np.array([1,0,4,3])) 
    

array([0, 1, 3, 4])

In [54]:
#ordinare gli indici
np.argsort(np.array([1,0,4,3]))

array([1, 0, 3, 2], dtype=int64)

In [55]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [56]:
a = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
b = np.array([[0, 2, 4, 6], [1, 3, 5, 7]])
np.concatenate((a,b),axis=1) #asse è sinonimo di dimensione

array([[1, 2, 3, 4, 0, 2, 4, 6],
       [5, 6, 7, 8, 1, 3, 5, 7]])

In [57]:
#reshape an array:
a = np.arange(6) # --> crea array [0,1,2,3,4,5]
a.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [58]:
# un array standard ha una sola dimension
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [59]:
# per trasformarlo in un array con due dimensioni:
a2 = a[np.newaxis, :]

In [60]:
a2.shape

(1, 6)

In [61]:
#SLICING
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a[0:2] # si fa slicing come nelle liste

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [62]:
a[( a < 6 ) | (a > 9)] # slicing condizionale

array([ 1,  2,  3,  4,  5, 10, 11, 12])

In [63]:
a1 = np.array([[1, 1],[2, 2]])
a2 = np.array([[3, 3],[4, 4]])

In [64]:
#alternativa a concatenate
np.vstack((a1,a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [66]:
np.hstack((a1,a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

# DIFFERENZA TRA ARRAY e MATRICI
### `np.array`

- **Generico**: `np.array` è un array generico che può essere usato per rappresentare vettori, matrici e n-d array.
- **Operazioni element-wise**: Le operazioni aritmetiche su `np.array` sono eseguite elemento per elemento (element-wise).
- **Dimensioni**: Può avere più di due dimensioni.
- **Metodi di creazione**: Si usa `numpy.array()` per creare un array.
- **Versatilità**: Può rappresentare sia vettori che matrici e supporta broadcasting, indexing, slicing, ecc.


In [67]:
array = np.array([[1, 2], [3, 4]])
print(array)

# Operazione element-wise
print("\nrisultato array * array:")
print(array * array)



[[1 2]
 [3 4]]

risultato array * array:
[[ 1  4]
 [ 9 16]]



### `np.matrix`

- **Specializzato**: `np.matrix` è una classe specifica per rappresentare matrici (solo 2D).
- **Operazioni di algebra lineare**: Le operazioni aritmetiche su `np.matrix` sono operazioni di algebra lineare. Ad esempio, l'operatore `*` esegue la moltiplicazione tra matrici.
- **Sempre 2D**: `np.matrix` è sempre bidimensionale.
- **Metodi di creazione**: Si usa `numpy.matrix()` o `numpy.mat()` per creare una matrice.
- **Deprecato**: L'uso di `np.matrix` è sconsigliato e considerato deprecato perché `np.array` è più flessibile e integrato con il resto dell'ecosistema numpy.


In [68]:
matrix = np.matrix([[1, 2], [3, 4]])
print(matrix)
# Output:
# [[1 2]
#  [3 4]]

# Operazione di algebra lineare
print("\nrisultato operazione matrix * matrix")
print(matrix * matrix)
# Output:
# [[ 7 10]
#  [15 22]]


[[1 2]
 [3 4]]

risultato operazione matrix * matrix
[[ 7 10]
 [15 22]]
