In [2]:
import numpy as np

In [3]:
arr = np.array([[4.2,2],[0,0],[0.4,12]])

In [4]:
arr

array([[ 4.2,  2. ],
       [ 0. ,  0. ],
       [ 0.4, 12. ]])

In [5]:
arr.shape

(3, 2)

In [6]:
arr.reshape(2,3)

array([[ 4.2,  2. ,  0. ],
       [ 0. ,  0.4, 12. ]])

In [7]:
arr.dtype

dtype('float64')

In [8]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [9]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.empty(10)

array([nan,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [21]:
arr_0 = np.ones_like(arr)
arr_0

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [34]:
arr = np.eye(6, dtype="int32")

# Aritmetica con Numpy Array 

In [53]:
arr = np.arange(1,24,2)

In [54]:
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [55]:
arr = arr.reshape(4,3)

In [56]:
arr

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23]])

In [57]:
1/arr

array([[1.        , 0.33333333, 0.2       ],
       [0.14285714, 0.11111111, 0.09090909],
       [0.07692308, 0.06666667, 0.05882353],
       [0.05263158, 0.04761905, 0.04347826]])

In [58]:
arr*2

array([[ 2,  6, 10],
       [14, 18, 22],
       [26, 30, 34],
       [38, 42, 46]])

In [59]:
arr + 1

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24]])

In [61]:
arr[0:3]

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [64]:
arr[1:][:-1]

array([[ 7,  9, 11],
       [13, 15, 17]])

# moltiplicazione matriciale tra array

In [72]:
array = np.array([[1, 2], [3, 4]])
array@array.T

array([[ 5, 11],
       [11, 25]])

In [73]:
# oppure
array.dot(array.T)

array([[ 5, 11],
       [11, 25]])

In [74]:
# o ancora
np.dot(array,array.T)

array([[ 5, 11],
       [11, 25]])

# ESERCIZIETTI
- Crea un array di dimensione 10 che vada da 1 a 100 di passo 10
- Crea un array di shape (3,2) con i quadrati dei primi 6 numeri
- 