<div>
<img src="https://upload.wikimedia.org/wikipedia/commons/3/31/NumPy_logo_2020.svg" width="500"/>
</div>


In [2]:
import numpy as np
# https://numpy.org/doc/stable/reference/arrays.html

### N-dimensional array Object detto anche ndarray

In [11]:
arr = np.array([[0,0,0,0], [0,3,2,0]]) # matrice 2 righe e 4 colonne
print(arr)

[[0 0 0 0]
 [0 3 2 0]]


In [12]:
arr.dtype
#arr.size

dtype('int32')

In [16]:
arr2 = np.atleast_2d(np.array([0,1,2,3,4]))

In [17]:
arr2.shape

(1, 5)

In [18]:
arr.dtype

dtype('int32')

In [19]:
arr3 = np.array([[0,0,0,0], [0,3,2,0]], dtype=np.float64)

In [20]:
arr3

array([[0., 0., 0., 0.],
       [0., 3., 2., 0.]])

In [21]:
arr3.dtype

dtype('float64')

#Possiamo trasformare il tipo di dati contenuti in un array con il metodo astype(nuovo_tipo)

In [22]:
arr3.astype(np.int32)

array([[0, 0, 0, 0],
       [0, 3, 2, 0]])

In [25]:
mat = np.mat('1.23 2 ; 3 4') #deprecato

In [24]:
print(mat)

[[1.23 2.  ]
 [3.   4.  ]]


In [28]:
arr.all()
#arr.any()

False

In [29]:
arr.argmax()

5

In [34]:
arr2 = np.arange(1,5,1.5) # crea un array intero crescente a partire da 0 range

In [35]:
arr2

array([1. , 2.5, 4. ])

In [18]:
l=[1,2]

## Trasformare una lista in un array

In [19]:
np.asarray(l)

array([1, 2])

In [21]:
l?

Type:        list
String form: [1, 2]
Length:      2
Docstring:  
Built-in mutable sequence.

If no argument is given, the constructor creates a new empty list.
The argument must be an iterable if specified.


In [43]:
a=np.full(3,np.int32)

In [44]:
a

array([<class 'numpy.int32'>, <class 'numpy.int32'>,
       <class 'numpy.int32'>], dtype=object)

### funzioni di creazione:
- array
- asarray
- arange
- ones
- ones_like
- zeros
- zeros_like
- empty
- empty_like
- full
- full_like
- eye, identity

# Differenze tra np.arange e range
- tipo di ritorno
- efficienza su grandi numeri (dimostriamolo)
- limitazioni di range (opera solo su interi (dimostriamolo))

### Aritmetica con Numpy

In [37]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [38]:
arr.shape = (5,2)
print(arr)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [49]:
ris = arr*arr
print(ris)

[[ 0  1]
 [ 4  9]
 [16 25]
 [36 49]
 [64 81]]


In [50]:
ris*10

array([[  0,  10],
       [ 40,  90],
       [160, 250],
       [360, 490],
       [640, 810]])

In [51]:
1/ris

C:\Users\iapi9\AppData\Local\Temp\ipykernel_11248\2141604455.py:1: RuntimeWarning: divide by zero encountered in divide
  1/ris


array([[       inf, 1.        ],
       [0.25      , 0.11111111],
       [0.0625    , 0.04      ],
       [0.02777778, 0.02040816],
       [0.015625  , 0.01234568]])

In [52]:
ris > 30

array([[False, False],
       [False, False],
       [False, False],
       [ True,  True],
       [ True,  True]])

In [79]:
ris[3][:]

array([36, 49])

In [53]:
ris[2:4][:] = 99

In [54]:
ris

array([[ 0,  1],
       [ 4,  9],
       [99, 99],
       [99, 99],
       [64, 81]])

In [86]:
ris_copy = ris[2:4][:].copy()
print(ris_copy)

[[99 99]
 [99 99]]


In [55]:
arr3d = np.random.rand(4,3,5,9)
print(arr3d)

[[[[0.50078505 0.87746531 0.83741069 0.88351572 0.40946614 0.77712427
    0.20551916 0.3170947  0.79584431]
   [0.45522528 0.15338779 0.08522945 0.41457455 0.68563635 0.11771221
    0.13212141 0.09390872 0.2218901 ]
   [0.6347324  0.69995481 0.14774031 0.04808505 0.22443178 0.8633191
    0.75350332 0.1703085  0.16727201]
   [0.46672349 0.47357259 0.14788725 0.85596993 0.40697642 0.89933917
    0.42927006 0.76584711 0.13935699]
   [0.79388226 0.53231952 0.96209644 0.58894586 0.66141276 0.71221371
    0.35097815 0.50111054 0.36121367]]

  [[0.29005585 0.69197166 0.77174005 0.04575901 0.87020368 0.92124951
    0.74977023 0.55669516 0.26756245]
   [0.53926882 0.03219265 0.75678939 0.65779881 0.25070091 0.76372775
    0.62171038 0.44280627 0.12982522]
   [0.8575789  0.04908257 0.21396084 0.80485808 0.40968756 0.28486201
    0.57188685 0.38499255 0.75205038]
   [0.63332504 0.47550643 0.91843804 0.79123133 0.59246483 0.71989591
    0.32103619 0.49726396 0.841561  ]
   [0.24802166 0.70793345 0

## Indicizzazione Booleana

In [58]:
data = np.array([[4,7],[0,2],[.5,6],[-7.1,32],[0,0],[1,2.4]])
names = np.array(["Bob","John","Mark","Bob","Bob","Tom"])

In [61]:
data

array([[ 4. ,  7. ],
       [ 0. ,  2. ],
       [ 0.5,  6. ],
       [-7.1, 32. ],
       [ 0. ,  0. ],
       [ 1. ,  2.4]])

In [62]:
names=="Bob"

array([ True, False, False,  True,  True, False])

In [121]:
data[names=="Bob"]

array([[ 4. ,  7. ],
       [-7.1, 32. ],
       [ 0. ,  0. ]])

In [132]:
data[~(names=="Bob")]

array([[0. , 2. ],
       [0.5, 6. ],
       [1. , 2.4]])

# Differenza tra liste e numpy array
- Le liste sono native di python, mentre gli array sono della libreria numpy
- Le liste possono contenere tipi eterogenei, mentre gli array hanno elementi omogenei (o meglio *dovrebbero*)

# Perché usare gli array con numpy
Gli array hanno avanzati metodi di manipolazione dati che sono sia più facili per il programmatore sia più efficienti rispetto alle liste. 
Dunque per calcoli onerosi è consigliato usare quest'ultimi

## Esempio:

In [66]:
lista1 = [1,2,3]
lista2 = [7,8,9]
print(lista1 + lista2)
somma = []
for x,y in zip(lista1,lista2):
    somma.append(x+y)
print(somma)

[1, 2, 3, 7, 8, 9]
[8, 10, 12]


In [67]:
arr1 = np.array([1,2,3])
arr2 = np.array([7,8,9])
arr1 + arr2

array([ 8, 10, 12])

# Dimostriamo l'efficienza nel sommare array rispetto a liste. 
SIZE consigliata: 100000

In [69]:
import time
# Defining the size of the arrays
SIZE = 1000000

# Creating lists and NumPy arrays of integers from 0 to SIZE - 1
list1 = range(SIZE)
list2 = range(SIZE)
arra1 = np.arange(SIZE)
arra2 = np.arange(SIZE)

# Measuring the time taken to aggregate elements from each iterable using a list comprehension
start_list = time.time()  # Marking the start time
result = [x+y for x, y in zip(list1, list2)]  # Aggregating elements from 'list1' and 'list2' using list comprehension
print("Time to aggregate elements from each of the iterables:")
print("List:")
print((time.time() - start_list) * 1000)  # Printing the execution time in milliseconds

# Measuring the time taken to add NumPy arrays element-wise
start_array = time.time()  # Marking the start time
result = arra1 + arra2  # Performing element-wise addition on 'arra1' and 'arra2' using NumPy
print("NumPy array:")
print((time.time() - start_array) * 1000)  # Printing the execution time in milliseconds


Time to aggregate elements from each of the iterables:
List:
222.9592800140381
NumPy array:
26.99875831604004


In [78]:
diag = np.identity(5, dtype=int)
ones = np.ones(5)
zeros = np.zeros(5)
lin = np.linspace(0, 20, num=12)
lin # che differenze noti tra linspace e arange?

array([ 0.        ,  1.81818182,  3.63636364,  5.45454545,  7.27272727,
        9.09090909, 10.90909091, 12.72727273, 14.54545455, 16.36363636,
       18.18181818, 20.        ])

In [74]:
diag

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [75]:
emp = np.empty(5) # crea un array vuoto. Vuoto nel senso che non cambia lo stato delle celle di memoria che vengono assegnate all'array

In [76]:
emp

array([1.24263877e-311, 4.67296746e-307, 1.69121096e-306, 1.42417901e-306,
       1.84565979e-317])

In [157]:
lin

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. ])

In [158]:
diag*[5,4,3,2,1] #supporta anche la moltiplicazione con scalari

array([[5, 0, 0, 0, 0],
       [0, 4, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 2, 0],
       [0, 0, 0, 0, 1]])

In [85]:
ris = np.ones((5,3))*[5,4,3]
ris

array([[5., 4., 3.],
       [5., 4., 3.],
       [5., 4., 3.],
       [5., 4., 3.],
       [5., 4., 3.]])

In [86]:
newd = diag*[2,0,1,3,0] #supporta la moltiplicazione tra liste e array (compatibilmente con le regole di moltiplicazione matriciale)
newd

array([[2, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 0]])

In [89]:
conc = np.sort(newd, axis=1) # ordina gli array

In [90]:
conc

array([[0, 0, 0, 0, 2],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 3],
       [0, 0, 0, 0, 0]])

In [168]:
# ordinare un array
np.sort(np.array([1,0,4,3])) 
    

array([0, 1, 3, 4])

In [91]:
#ordinare gli indici
np.argsort(np.array([1,9,4,3]))

array([0, 3, 2, 1], dtype=int64)

In [99]:
a = np.atleast_2d(np.array([1, 2, 3, 4]))
b = np.atleast_2d(np.array([5, 6, 7, 8]))
np.concatenate((a,b), axis=0)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [102]:
a = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
b = np.array([[0, 2, 4, 6], [1, 3, 5, 7]])
np.concatenate((a,b),axis=1) #asse è sinonimo di dimensione

array([[1, 2, 3, 4, 0, 2, 4, 6],
       [5, 6, 7, 8, 1, 3, 5, 7]])

In [109]:
#reshape an array:
a = np.arange(6) # --> crea array [0,1,2,3,4,5]
b = a.reshape(2,3)

In [111]:
a.shape

(6,)

In [116]:
# per trasformarlo in un array con due dimensioni:
a2 = a[np.newaxis, :]
a3 = np.atleast_2d(a).T

In [117]:
a2.shape

(1, 6)

In [118]:
a3.shape

(6, 1)

In [119]:
#SLICING
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a # si fa slicing come nelle liste

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [120]:
a[( a < 6 ) | (a > 9)] # slicing condizionale

array([ 1,  2,  3,  4,  5, 10, 11, 12])

In [126]:
a1 = np.array([[1, 1],[2, 2]])
a2 = np.array([[3, 3],[4, 4]])

In [134]:
#alternativa a concatenate
np.vstack((a1,a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [135]:
np.hstack((a1,a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

# DIFFERENZA TRA ARRAY e MATRICI
### `np.array`

- **Generico**: `np.array` è un array generico che può essere usato per rappresentare vettori, matrici e n-d array.
- **Operazioni element-wise**: Le operazioni aritmetiche su `np.array` sono eseguite elemento per elemento (element-wise).
- **Dimensioni**: Può avere più di due dimensioni.
- **Metodi di creazione**: Si usa `numpy.array()` per creare un array.
- **Versatilità**: Può rappresentare sia vettori che matrici e supporta broadcasting, indexing, slicing, ecc.


In [67]:
array = np.array([[1, 2], [3, 4]])
print(array)

# Operazione element-wise
print("\nrisultato array * array:")
print(array * array)



[[1 2]
 [3 4]]

risultato array * array:
[[ 1  4]
 [ 9 16]]



### `np.matrix`

- **Specializzato**: `np.matrix` è una classe specifica per rappresentare matrici (solo 2D).
- **Operazioni di algebra lineare**: Le operazioni aritmetiche su `np.matrix` sono operazioni di algebra lineare. Ad esempio, l'operatore `*` esegue la moltiplicazione tra matrici.
- **Sempre 2D**: `np.matrix` è sempre bidimensionale.
- **Metodi di creazione**: Si usa `numpy.matrix()` o `numpy.mat()` per creare una matrice.
- **Deprecato**: L'uso di `np.matrix` è sconsigliato e considerato deprecato perché `np.array` è più flessibile e integrato con il resto dell'ecosistema numpy.


In [68]:
matrix = np.matrix([[1, 2], [3, 4]])
print(matrix)
# Output:
# [[1 2]
#  [3 4]]

# Operazione di algebra lineare
print("\nrisultato operazione matrix * matrix")
print(matrix * matrix)
# Output:
# [[ 7 10]
#  [15 22]]


[[1 2]
 [3 4]]

risultato operazione matrix * matrix
[[ 7 10]
 [15 22]]


# moltiplicazione matriciale tra array

In [121]:
array = np.array([[1, 2], [3, 4]])
array@array

array([[ 7, 10],
       [15, 22]])

In [122]:
# oppure
array.dot(array)

array([[ 7, 10],
       [15, 22]])

In [123]:
# o ancora
np.dot(array,array)

array([[ 7, 10],
       [15, 22]])

In [124]:
a = np.atleast_2d([1,2,3])
b = np.atleast_2d([4,5,6])

In [128]:
a

array([[1, 2, 3]])

In [129]:
b

array([[4, 5, 6]])

In [133]:
a.T@b

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

In [134]:
a@b.T

array([[32]])

# il prodotto interno di due vettori:

In [212]:
v1 = np.array([3.2, 2.4, 4.1, 2.1])
v2 = np.array([2.21, 3., 4.2, 1.3])
pr_int_1 = np.sum( v1 * v2 ) #prodotto interno

# vediamo l'algoritmo nel dettaglio di un'implementazione scalare:
pr_int_2 = 0.0
for i in range(len(v1)):
    pr_int_2 += v1[i] * v2[i]
#endfor

# possiamo anche vedere il prodotto interno di due vettori come un caso particolare 
# di prodotto di matrici:
r = np.atleast_2d(v1)  # vettore "riga" (e quindi bi-dimensionale)
c = np.atleast_2d(v2).T  # vettore "colonna" (e quindi bi-dimensionale)
pr_int_3 = r @ c  # e' un caso particolare di prodotto di matrici

# confronto:
print("pr_int_1 = ",pr_int_1," , pr_int_2 = ",pr_int_2," , pr_int_3 = ",pr_int_3)
print('\n','''Notare che nel primo e secondo caso il risultato è uno scalare, mentre nel terzo è una matrice con un elemento; vettori e matrici con un elemento possono avere comportamenti controintuitivi, vedere "dimensioni_e_lunghezza_dei_vettori_numpy.ipynb''')

pr_int_1 =  34.221999999999994  , pr_int_2 =  34.221999999999994  , pr_int_3 =  [[34.222]]

 Notare che nel primo e secondo caso il risultato è uno scalare, mentre nel terzo è una matrice con un elemento; vettori e matrici con un elemento possono avere comportamenti controintuitivi, vedere "dimensioni_e_lunghezza_dei_vettori_numpy.ipynb


# il prodotto esterno di due vettori:

In [217]:
v1 = np.array([3.2, 2.4, 4.1, 2.1])
v2 = np.array([2.21, 3., 4.2, 1.3])
# possiamo vedere il prodotto esterno di due vettori come un caso particolare 
# di prodotto di matrici:
c = np.atleast_2d(v1).T  # vettore "colonna" (e quindi bi-dimensionale)
r = np.atleast_2d(v2)  # vettore "riga" (e quindi bi-dimensionale)
pr_est_1 = c @ r  # e' un caso particolare di prodotto di matrici

# vediamo l'algoritmo nel dettaglio di un'implementazione scalare:
pr_est_2 = np.zeros((len(v1),len(v2)))
for i in range(len(v1)):
    for j in range(len(v2)):
        pr_est_2[i,j] = v1[i] * v2[j]

# confronto:
print("pr_est_1 = \n",pr_est_1,"\npr_est_2 = \n",pr_est_2)
#print("np.sum(np.sum(np.abs(pr_int_1-pr_int_2))) = ",np.sum(np.sum(np.abs(pr_int_1-pr_int_2))))

pr_est_1 = 
 [[ 7.072  9.6   13.44   4.16 ]
 [ 5.304  7.2   10.08   3.12 ]
 [ 9.061 12.3   17.22   5.33 ]
 [ 4.641  6.3    8.82   2.73 ]] 
pr_est_2 = 
 [[ 7.072  9.6   13.44   4.16 ]
 [ 5.304  7.2   10.08   3.12 ]
 [ 9.061 12.3   17.22   5.33 ]
 [ 4.641  6.3    8.82   2.73 ]]


# Prodotto matrice/vettore


In [135]:
# il prodotto matrice-vettore:
# possiamo vedere il prodotto matrice-vettore come un caso particolare 
# di prodotto di matrici:
A = np.random.rand(4,5)  # matrice a valori pseudo-casuali
tmpv = np.array([2.21, 3., 4.2, 1.3, 4.4])
v = np.atleast_2d(tmpv).T  # vettore (bi-dimensionale) "colonna"
pr_Mv_1 = A @ v  # e' un caso particolare di prodotto di matrici

# vediamo l'algoritmo nel dettaglio di un'implementazione scalare:
pr_Mv_2 = np.zeros((A.shape[0],1)) # vettore colonna di zeri
for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        pr_Mv_2[i] += A[i,j] * v[j]
    #endfor
#endfor

# confronto:
print("np.sum(np.abs(pr_Mv_1-pr_Mv_2)) = ",np.sum(np.abs(pr_Mv_1-pr_Mv_2)))

np.sum(np.abs(pr_Mv_1-pr_Mv_2)) =  1.7763568394002505e-15


# Inversione di una matrice

In [138]:
X = np.random.randint(0, 10, size=(4, 4))
X

array([[8, 0, 1, 3],
       [9, 2, 3, 9],
       [6, 4, 9, 6],
       [4, 9, 1, 6]])

In [140]:
from numpy.linalg import inv
inv(X)


array([[ 0.20685435, -0.08200734,  0.00244798,  0.01713586],
       [ 0.05140759, -0.11505508,  0.01835985,  0.12851897],
       [-0.01958384, -0.05140759,  0.13586291, -0.04895961],
       [-0.21175031,  0.23582211, -0.05181559, -0.02937576]])

In [156]:
Id = X @ inv(X)
Id = np.around(Id).astype('int32')
Id

array([[ 1.,  0., -0.,  0.],
       [ 0.,  1., -0.,  0.],
       [-0., -0.,  1., -0.],
       [-0., -0., -0.,  1.]])

In [157]:
A = np.array([[1,1],[2,3]])
A

array([[1, 1],
       [2, 3]])

In [161]:
np.sin(A)

array([[0.84147098, 0.84147098],
       [0.90929743, 0.14112001]])

### Meotdi Numpy Veloci ELement-Wise
# Unarie
- sqrt
- exp
- abs
- log
- isnan, isinf
- floor
- cos, sin
- logical_not
- ecc
# Binarie
- add
- subtract
- multiply
- power
- maximum, minimum
- logical_and, logical_or
- greater
- -ecc

In [170]:
X1 = np.random.randint(1, 10, size=(4, 4))
X2 = np.random.randint(1, 10, size=(4, 4))
X1

array([[6, 4, 8, 6],
       [8, 6, 2, 7],
       [6, 6, 9, 6],
       [8, 9, 2, 3]])

In [171]:
X2

array([[5, 4, 4, 9],
       [9, 7, 9, 5],
       [1, 8, 6, 1],
       [1, 4, 3, 2]])

In [172]:
np.greater(X1,X2)

array([[ True, False,  True, False],
       [False, False, False,  True],
       [ True, False,  True,  True],
       [ True,  True, False,  True]])

### Metodi Statistici

In [181]:
arr = np.random.rand(3,5) #distribuzione uniforme tra 0 e 1. I parametri sono le dimensioni degli assi

In [182]:
arr

array([[0.94226035, 0.86686012, 0.33138264, 0.25180335, 0.58829865],
       [0.03259132, 0.10775001, 0.09096267, 0.99333988, 0.71276643],
       [0.60163646, 0.08822773, 0.20256835, 0.20082795, 0.47602791]])

In [183]:
arr.mean()

0.43248692037252157

In [184]:
arr.sum()

6.487303805587824

In [185]:
arr.cumsum()

array([0.94226035, 1.80912047, 2.14050311, 2.39230646, 2.9806051 ,
       3.01319642, 3.12094643, 3.2119091 , 4.20524897, 4.9180154 ,
       5.51965186, 5.60787959, 5.81044794, 6.01127589, 6.48730381])

### esportare o importare Numpyarray su e da file

In [189]:
arr = np.arange(15)
np.save("nome_file_array.npy",arr)

In [192]:
a_load = np.load("nome_file_array.npy")
a_load

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# ESERCIZIETTI
- Crea un array di dimensione 10 che vada da 1 a 100 di passo 10
- Crea un array che vada da 1 a 1000 con 30 numeri dentro. 1000 escluso
- Crea un array di shape (3,2) con i quadrati dei primi 6 numeri
- Cosa succede se faccio cumsum su un array di più di una dimensione?
- Cosa succede se allo slice di un array assegno un un solo valore scalare? e all'array di partenza cosa succede?
- Crea una array di dimensioni (5,3) che abbia sulla prima e ultima riga zero, mentre sulle altre 1
- Crea un vettore di meno uni di shape 3x4
- Facciamo il prodotto tra due matrici sia con le funzionalità numpy che attraverso due cicli in python. Valutiamone anche le performance

In [194]:
persone = np.array(["susanna","rebecca","michael","riccardo"])
persone[np.random.randint(0,4)]

'michael'

In [ ]:
np.linspace(